version: '2'
services:
  web:
    image: joaquimsimao2009/site-treinamento:v1
    build: .
    container_name: site3
    restart: always
    ports:
      - '8023:80'
  web2:
    image: joaquimsimao2009/site-treinamento:v2   
    container_name: site2
    restart: always
    ports:
      - '8024:80'